name: smart_home_app
description: "Flutter Smart Home IoT Control Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP Client & Networking
  dio: ^5.3.2

  # MQTT Client
  mqtt_client: 10.11.0

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  fl_chart: ^1.1.0

  # Permissions & Device
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # Utilities
  intl: ^0.19.0
  uuid: ^4.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/

  # Fonts (Google Fonts will handle Roboto automatically)
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
