version: "3.8"

services:
  smart-home-server:
    build: .
    container_name: smart-home-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SERVER_IP=35.247.182.78
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - OPENAI_API_KEY=your-openai-api-key-here
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - smart-home-network

networks:
  smart-home-network:
    driver: bridge
